#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative 'lexer'

class Calculator < Racc::Parser

module_eval(<<'...end test_language.y/module_eval...', 'test_language.y', 28)
  def parse(input)
    scan_str(input)
  end
...end test_language.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,     3,    14,     6,     7,     8,     9,    10,    11,    12,
    13,     3,    16,    17,    18,    19 ]

racc_action_check = [
     1,     5,     4,     1,     1,     1,     1,     3,     3,     3,
     3,     0,    10,    11,    12,    13 ]

racc_action_pointer = [
     9,     0,   nil,     4,     2,    -1,   nil,   nil,   nil,   nil,
    10,    11,    12,    13,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -12,   -12,    -1,    -3,   -12,   -12,    -8,    -9,   -10,   -11,
   -12,   -12,   -12,   -12,    20,    -2,    -4,    -5,    -6,    -7 ]

racc_goto_table = [
     2,     1,     5,   nil,   nil,    15 ]

racc_goto_check = [
     2,     1,     3,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,     0,     1 ]

racc_goto_default = [
   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 8, :_reduce_1,
  3, 8, :_reduce_2,
  1, 9, :_reduce_none,
  3, 9, :_reduce_4,
  3, 9, :_reduce_5,
  3, 9, :_reduce_6,
  3, 9, :_reduce_7,
  1, 10, :_reduce_none,
  1, 10, :_reduce_none,
  1, 10, :_reduce_none,
  1, 10, :_reduce_none ]

racc_reduce_n = 12

racc_shift_n = 20

racc_token_table = {
  false => 0,
  :error => 1,
  :DIGIT => 2,
  :ADD => 3,
  :SUBSTRACT => 4,
  :MULTIPLY => 5,
  :DIVIDE => 6 }

racc_nt_base = 7

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DIGIT",
  "ADD",
  "SUBSTRACT",
  "MULTIPLY",
  "DIVIDE",
  "$start",
  "Expressions",
  "Expression",
  "Operation" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'test_language.y', 3)
  def _reduce_1(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'test_language.y', 4)
  def _reduce_2(val, _values, result)
     return val[0].send(val[1], val[2]) 
    result
  end
.,.,

# reduce 3 omitted

module_eval(<<'.,.,', 'test_language.y', 9)
  def _reduce_4(val, _values, result)
     return val[0] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'test_language.y', 10)
  def _reduce_5(val, _values, result)
     return val[0] - val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'test_language.y', 11)
  def _reduce_6(val, _values, result)
     return val[0] * val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'test_language.y', 12)
  def _reduce_7(val, _values, result)
     return val[0] / val[2] 
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Calculator
